{% extends "include/base.phtml" %}

{% block meta %}
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <link href="<?php echo $statics_url ?>assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $statics_url ?>assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
        <!-- END PAGE LEVEL PLUGINS -->
        <link href="<?php echo $statics_url ?>assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
        <!-- BEGIN THEME GLOBAL STYLES -->
        <link href="<?php echo $statics_url ?>assets/global/css/components.min.css" rel="stylesheet" id="style_components" type="text/css" />
        <link href="<?php echo $statics_url ?>assets/global/css/plugins.min.css" rel="stylesheet" type="text/css" />
        <!-- END THEME GLOBAL STYLES -->
        <!-- BEGIN THEME LAYOUT STYLES -->
        <link href="<?php echo $statics_url ?>assets/layouts/layout/css/layout.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $statics_url ?>assets/layouts/layout/css/themes/darkblue.min.css" rel="stylesheet" type="text/css" id="style_color" />
        <link href="<?php echo $statics_url ?>assets/layouts/layout/css/custom.min.css" rel="stylesheet" type="text/css" />
        <!-- END THEME LAYOUT STYLES -->
{% endblock %}

{% block content %}
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <!-- BEGIN CONTENT BODY -->
    <div class="page-content" style="min-height:1432px">
        <!-- BEGIN PAGE HEADER-->

        <!-- BEGIN PAGE BAR -->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="/">首页</a>
                    <i class="fa fa-circle"></i>
                </li>
                <li>
                    <a href="/monit">监控管理</a>
                </li>

            </ul>

        </div>
        <!-- END PAGE BAR -->
        <!-- BEGIN PAGE TITLE-->
        <h3 class="page-title"> 监控管理</h3>
        <!-- END PAGE TITLE-->
        <!-- END PAGE HEADER-->

        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet light bordered">
                    <div class="portlet-body">

                        <table id="item_list" class="table table-striped table-bordered table-hover table-checkable order-column">
                            <thead>
                            <tr>
                                <th>
                                    <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                        <input type="checkbox" class="group-checkable" data-set="#item_list .checkboxes" />
                                        <span></span>
                                    </label>
                                </th>
                                <th> 项目名称 </th>
                                <th> 报警方式 </th>
                                <th> 慢报警 </th>
                                <th> 错误报警 </th>
                                <th> 操作 </th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>

                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>


    </div>
    <!-- END CONTENT BODY -->
</div>
<!-- END CONTENT -->
{% endblock %}
{% block footer %}
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="<?php echo $statics_url ?>assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
        <script src="<?php echo $statics_url ?>assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL SCRIPTS -->
        <script src="<?php echo $statics_url ?>assets/global/scripts/app.min.js" type="text/javascript"></script>
        <!-- END THEME GLOBAL SCRIPTS -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="<?php echo $statics_url ?>assets/global/plugins/bootbox/bootbox.min.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS -->
        <script src="<?php echo $statics_url ?>assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
        <!-- BEGIN THEME LAYOUT SCRIPTS -->
        <script src="<?php echo $statics_url ?>assets/layouts/layout/scripts/layout.min.js" type="text/javascript"></script>
        <script src="<?php echo $statics_url ?>assets/layouts/global/scripts/quick-sidebar.min.js" type="text/javascript"></script>
        <!-- END THEME LAYOUT SCRIPTS -->

        <script src="<?php echo $statics_url ?>assets/am/scripts/monit.js" type="text/javascript"></script>
        <!-- START 修改项目 -->
        <div id="editModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <h4 class="modal-title">修改项目</h4>
                    </div>
                    <div id="form_alert" style="padding:10px 20px 0 20px"> </div>
                    <form id="add-form"  method="post" class="form-horizontal" role="form">
                        <div class="modal-body">
                            <div class="form-body">
                                <div class="form-group">
                                    <label class="col-md-3 control-label">项目名称</label>
                                    <div class="col-md-9">
                                        <div class="input-inline input-medium">
                                            <div class="input-group">
                                                <input type="text" name="pname" class="form-control placeholder-no-fix" autocomplete="off" placeholder="">
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-3 control-label">报警方式</label>
                                    <div class="col-md-9">
                                        <div class="mt-checkbox-inline">
                                            <label class="mt-checkbox">
                                                <input type="checkbox" name="alarm_mode" value="1"> 邮件
                                                <span></span>
                                            </label>
                                            <label class="mt-checkbox">
                                                <input type="checkbox" name="alarm_mode" value="2"> 短信
                                                <span></span>
                                            </label>
                                            <label class="mt-checkbox">
                                                <input type="checkbox" name="alarm_mode" value="3"> 电话
                                                <span></span>
                                            </label>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-3 control-label">报警邮箱</label>
                                    <div class="col-md-9">
                                        <div class="input-inline input-medium">
                                            <div class="input-group">
                                                <textarea class="form-control" rows="3" cols="60" name="alarm_email"></textarea>
                                            </div>
                                        </div>
                                        <span class="help-inline"> 可填写多个邮箱地址，每行一个</span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-3 control-label">报警手机</label>
                                    <div class="col-md-9">
                                        <div class="input-inline input-medium">
                                            <div class="input-group">
                                                <textarea class="form-control" rows="3" cols="60" name="alarm_mobile"></textarea>
                                            </div>
                                        </div>
                                        <span class="help-inline"> 可填写多个手机号码，每行一个</span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-3 control-label">慢报警</label>
                                    <div class="col-md-9">
                                        <input type="checkbox" id="slow_alarm" name="slow_alarm" class="make-switch" data-on-color="success" data-off-color="warning">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-3 control-label">时间阀值(ms)</label>
                                    <div class="col-md-9">
                                        <div class="input-inline input-medium">
                                            <div class="input-group">
                                                <input type="text" name="slow_time" class="form-control placeholder-no-fix" autocomplete="off" placeholder="1000">
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-3 control-label">错误报警</label>
                                    <div class="col-md-9">
                                        <input type="checkbox" id="error_alarm" name="error_alarm" class="make-switch" data-on-color="success" data-off-color="warning">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-3 control-label">错误状态码</label>
                                    <div class="col-md-9">
                                        <div class="input-inline input-medium">
                                            <div class="input-group">
                                                <input type="text" name="error_status" class="form-control placeholder-no-fix" autocomplete="off" placeholder="500">
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>

                        </div>
                        <div class="modal-footer">
                            <input type="hidden" name="pid" value="" />
                            <input type="button" id="save-btn" class="btn yellow submit-btn" value="保存" />
                            <button class="btn default" data-dismiss="modal" aria-hidden="true">关闭</button>

                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- END 修改项目 -->

{% endblock %}