{% extends "include/base.phtml" %}

{% block meta %}
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <link href="<?php echo $statics_url ?>assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $statics_url ?>assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL STYLES -->
        <link href="<?php echo $statics_url ?>assets/global/css/components.min.css" rel="stylesheet" id="style_components" type="text/css" />
        <link href="<?php echo $statics_url ?>assets/global/css/plugins.min.css" rel="stylesheet" type="text/css" />
        <!-- END THEME GLOBAL STYLES -->
        <!-- BEGIN THEME LAYOUT STYLES -->
        <link href="<?php echo $statics_url ?>assets/layouts/layout/css/layout.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $statics_url ?>assets/layouts/layout/css/themes/darkblue.min.css" rel="stylesheet" type="text/css" id="style_color" />
        <link href="<?php echo $statics_url ?>assets/layouts/layout/css/custom.min.css" rel="stylesheet" type="text/css" />
        <!-- END THEME LAYOUT STYLES -->
{% endblock %}

{% block content %}
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <!-- BEGIN CONTENT BODY -->
    <div class="page-content" style="min-height:1432px">
        <!-- BEGIN PAGE HEADER-->

        <!-- BEGIN PAGE BAR -->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="/">首页</a>
                    <i class="fa fa-circle"></i>
                </li>
                <li>
                    <a href="/{{controller}}">{{controller_name}}</a>
                </li>

            </ul>

        </div>
        <!-- END PAGE BAR -->
        <!-- BEGIN PAGE TITLE-->
        <h3 class="page-title"> {{controller_name}}</h3>
        <!-- END PAGE TITLE-->
        <!-- END PAGE HEADER-->

        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet light bordered">
                    <div class="portlet-body">
                        <div class="table-toolbar">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="btn-group">
                                        <a id="add-btn" role="button" class="btn green" data-toggle="modal"> <i class="fa fa-plus"></i> 新增 </a>
                                    </div>
                                    <div class="btn-group">
                                        <a id="batch-del-btn" role="button" class="btn red-sunglo" data-toggle="modal">  <i class="fa fa-remove"></i> 批量删除</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <table id="item_list" class="table table-striped table-bordered table-hover table-checkable order-column">
                            <thead>
                            <tr>
                                <th>
                                    <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                        <input type="checkbox" class="group-checkable" data-set="#item_list .checkboxes" />
                                        <span></span>
                                    </label>
                                </th>
                                <th> 用户名 </th>
                                <th> 角色 </th>
                                <th> 手机 </th>
                                <th> 状态 </th>
                                <th> 添加时间 </th>
                                <th> 操作 </th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>

                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>


    </div>
    <!-- END CONTENT BODY -->
</div>
<!-- END CONTENT -->
{% endblock %}
{% block footer %}
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="<?php echo $statics_url ?>assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
        <script src="<?php echo $statics_url ?>assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL SCRIPTS -->
        <script src="<?php echo $statics_url ?>assets/global/scripts/app.min.js" type="text/javascript"></script>
        <!-- END THEME GLOBAL SCRIPTS -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="<?php echo $statics_url ?>assets/global/plugins/bootbox/bootbox.min.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME LAYOUT SCRIPTS -->
        <script src="<?php echo $statics_url ?>assets/layouts/layout/scripts/layout.min.js" type="text/javascript"></script>
        <script src="<?php echo $statics_url ?>assets/layouts/global/scripts/quick-sidebar.min.js" type="text/javascript"></script>
        <!-- END THEME LAYOUT SCRIPTS -->

        <script src="<?php echo $statics_url ?>assets/am/scripts/user.js" type="text/javascript"></script>
        <!-- START 修改用户 -->
        <div id="editModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <h4 class="modal-title">修改用户</h4>
                    </div>
                    <div id="form_alert" style="padding:10px 20px 0 20px"> </div>
                    <form id="add-form"  method="post" class="form-horizontal" role="form">
                        <div class="modal-body">
                            <div class="form-body">
                                <div class="form-group">
                                    <label class="col-md-3 control-label">用户名</label>
                                    <div class="col-md-9">
                                        <div class="input-inline input-medium">
                                            <div class="input-group">
                                                                    <span class="input-group-addon">
                                                                        <i class="fa fa-user"></i>
                                                                    </span>
                                                <input type="text" name="username" class="form-control placeholder-no-fix" autocomplete="off" placeholder="">
                                            </div>
                                        </div>
                                        <span class="help-inline"> (限制6-12位数字或字母) </span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-3 control-label">密码</label>
                                    <div class="col-md-9">
                                        <div class="input-inline input-medium">
                                            <div class="input-group">
                                                                    <span class="input-group-addon">
                                                                        <i class="fa fa-lock"></i>
                                                                    </span>
                                                <input id="newpassword" class="form-control" type="password" name="password" placeholder="">
                                            </div>
                                        </div>
                                        <span class="help-inline"> (限制6-12位数字或字母) </span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-3 control-label">角色</label>
                                    <div class="col-md-9">
                                        <select name="role" class="form-control input-medium">
                                            {% for role in role_list %}
                                            <option value="{{ role['rid'] }}"> {{ role['rname'] }}</option>
                                            {% endfor  %}
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-3 control-label">手机号码</label>
                                    <div class="col-md-9">
                                        <div class="input-inline input-medium">
                                            <div class="input-group">
                                                                    <span class="input-group-addon">
                                                                        <i class="fa fa-mobile"></i>
                                                                    </span>
                                                <input type="text" class="form-control" name="mobile" placeholder="">
                                            </div>
                                        </div>
                                        <span class="help-inline"> (限制11位数字) </span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-3 control-label">状态</label>
                                    <div class="col-md-9">
                                        <div class="mt-radio-inline">
                                            <label class="mt-radio">
                                                <input type="radio" name="status" id="optionsRadios22" value="1"> 启用
                                                <span></span>
                                            </label>
                                            <label class="mt-radio">
                                                <input type="radio" name="status" id="optionsRadios23" value="2"> 停用
                                                <span></span>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="modal-footer">
                            <input type="hidden" name="uid" value="" />
                            <input type="button" id="save-btn" class="btn yellow submit-btn" value="保存" />
                            <button class="btn default" data-dismiss="modal" aria-hidden="true">关闭</button>

                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- END 修改用户 -->

{% endblock %}